version: "3"

services:
  app:
    build:
      context: .
    command: npm run serve
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
    links:
      - db
  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
  redis:
    image: redis:6.0-alpine
