version: "3"

services:
  app:
    build:
      context: .
    command: npm run serve
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/usr/src/app
    links:
      - db
      - redis
  db:
    image: postgres:17-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
  redis:
    image: 'redis:7-alpine'
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
