onlyBuiltDependencies:
  - '@prisma/engines'
  - '@swc/core'
  - esbuild
  - prisma
  - msgpackr-extract
  - unrs-resolver

overrides:
  hono@<4.11.4: '>=4.11.4'
  hono@<4.11.7: '>=4.11.7'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  qs@<6.14.1: '>=6.14.1'
