openapi: 3.0.0
info:
  title: Test
  version: '1.0'
servers:
  - url: 'http://localhost:4000'
paths:
  /:
    get:
      summary: Root
      operationId: get-root
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  date_time:
                    type: string
